### ISSUE TITLE
windev

### ISSUE THREAD

**Issue by aloisdg** [jusdepatate/awesome-french#4]
Ah ouai.

**Comment by jusdepatate** [comment]
Desolé pour cette reponse tardive,
WinDev est un projet français d'une boîte française, de ce que j'en entends c'est un bon language, j'ai pu l'essayer et voir que c'était simple a prendre en main.
Si il y a un probleme avec WinDev, conformement a la "charte" des repos Awesome, je le supprimerai de la liste

**Comment by aloisdg** [comment]
Au dela d'être critiqué pour générer du code médiocre, il est surtout boycotté pour sa [communication carrément sexiste](http://www.mhfreq.org/2013/12/les-pubs-windev/).

**Comment by jusdepatate** [comment]
Et voila, merci de l'info
